name: Build and Publish Binary

on:
  push:
    tags:
      - "v*.*.*"  # Trigger on tag creation with versioning pattern
  workflow_dispatch:  # Allow manual runs from the GitHub Actions UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.18  # Use the Go version required by your project

    - name: Install Dependencies
      run: go mod tidy  # Ensures dependencies are properly installed

    - name: Build the binary
      run: |
        go build -o dist/image-optimizer  # Build binary with the name image-optimizer
      env:
        GOOS: linux   # You can specify other OS like windows or darwin (Mac)
        GOARCH: amd64 # Architecture type

    - name: Upload binary as artifact
      uses: actions/upload-artifact@v3
      with:
        name: image-optimizer
        path: dist/image-optimizer

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download built binary
      uses: actions/download-artifact@v3
      with:
        name: image-optimizer

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/image-optimizer
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
